export const Users = [
    {
      id:1,
      profilePicture: "assets/person/ts.jpg",
      username: "Taylor Swift",
    },
    {
      id:2,
      profilePicture: "assets/person/ag.jpg",
      username: "Ariana Grande",
    },
    {
      id:3,
      profilePicture: "assets/person/hp.avif",
      username: "Harry Potter",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "Luna Lovegood",
    },
    {
      id:5,
      profilePicture: "assets/person/kj.jpg",
      username: "Kendall Jenner",
    },
    {
      id:6,
      profilePicture: "assets/person/tonyy.jpg",
      username: "Tony Stark",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Kristina Thomas",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpeg",
      username: "Gary Bell",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "Sara James",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc:"Music is really Driving me!",
      photo: "assets/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Always.",
      photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc:"Never regret anything that made you smile.",
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc:"I Think Everyone is Beautiful in their Own Way.",
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc:"Never Stop Learning becoz Life Never Stops Teaching.",
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never Regret anything that made you Smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc:"Be You!",
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the World by being Yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc:"Storm in her Eyes, Peace in her Smile",
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];